CREATE TABLE Banking(ACCOUNT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
age INT ,
Gender VARCHAR(10),
Mobile_Number VARCHAR(13) UNIQUE,
PASSWORD VARCHAR(200),
Amount INT,
USER VARCHAR(10) DEFAULT 'User',
STATUS VARCHAR(20) DEFAULT 'Inactive'
);
SELECT * FROM Banking;
INSERT INTO 
Banking(ACCOUNT_NUMBER,NAME,age,Gender,Mobile_Number,PASSWORD,Amount,USER,STATUS) 
VALUES('663263','Admin','30','Male','7871170126','admin123','500','Admin','Active');
DROP TABLE Banking;
TRUNCATE TABLE Banking;